name: CI
on: push
jobs: 
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: |
          echo "hello "
          echo "hello priti"
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: run python
        run: python check.py
